services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - monitoring

  k6:
    image: grafana/k6:latest
    environment:
      # - K6_OUT=influxdb=http://influxdb:8086?org=myorg&bucket=k6&token=mytoken
      # - K6_OUT=influxdb=http://influxdb:8086/api/v2/write?bucket=k6&org=myorg
      - K6_OUT=influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORG=myorg
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_TOKEN=mytoken
    volumes:
      - ./k6:/scripts
    command: run /scripts/test.js
    depends_on:
      - influxdb
    networks:
      - monitoring

volumes:
  influxdb-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge